pentaho/pentaho-platform-plugin-reporting

test-src/org/pentaho/reporting/platform/plugin/ParameterTest.java

@mdamour1976, @pentaho-nbaker  It is fix for failed test for version 5.0. Could you review and merge it, please?

[TEST] Fix failed ParameterTest

---

src/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java
src/org/pentaho/reporting/platform/plugin/SimpleReportingComponent.java

Merge of master into future-develop

Auto-Merge refreshing development branch

---

src/org/pentaho/reporting/platform/plugin/connection/CdaPluginLocalQueryBackend.java

[PRD-5415] CDA Datasource in local API mode doesn't forward parameters to CDA

---

package-res/reportviewer/reportviewer-app.js
package-res/reportviewer/reportviewer-formatting.js
package-res/reportviewer/reportviewer-logging.js
package-res/reportviewer/reportviewer-main-module.js
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js

[BACKLOG-4054] 
- CDF version updated, where references to global CDF global variables were removed.
- Some references need to be reviewed
[BACKLOG-4124]
- Replaced CDF references in Report Viewer
- Removed direct dependencies to CDF libs (they are now fetched via the CDF code directly)
- Only tested in debug mode
- Unit tests not validated

BACKLOG-4054 & BACKLOG-4124

---

package-res/reportviewer/reportviewer-prompt.js

- Fixed small issue where the glass pane was preventing the user from changing his selection when Auto-Submit wasn't checked;

[BACKLOG-4038] - Review the prompting lifecycle

---

src/org/pentaho/reporting/platform/plugin/connection/PentahoMondrianConnectionProvider.java
src/org/pentaho/reporting/platform/plugin/drilldown/ContentLinkFunction.java
src/org/pentaho/reporting/platform/plugin/drilldown/IsContentLinkFunction.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoMondrianConnectionProviderTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoMondrianDataSourceProviderTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoOlap4JJndiConnectionProviderTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConfigReadHandlerTest.java
test-src/org/pentaho/reporting/platform/plugin/drilldown/ContentLinkFunctionDescriptionTest.java
test-src/org/pentaho/reporting/platform/plugin/drilldown/ContentLinkFunctionTest.java
test-src/org/pentaho/reporting/platform/plugin/drilldown/IsContentLinkFunctionDescriptionTest.java
test-src/org/pentaho/reporting/platform/plugin/drilldown/IsContentLinkFunctionTest.java

- Increased unit test coverage;
- Applied CheckStyle to existing classes;

[BACKLOG-5384, TEST, CLEANUP] - Increase unit test coverage

---

src/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java
test-src/org/pentaho/reporting/platform/plugin/ReportingActionIT.java

- Check if input is instance of RepositoryFileInputStream and generate report via it's file id
- Added tests
- Checkstyle applied
@tmorgner , @pentaho-nbaker , review it please.

[BISERVER-11556] - Scheduled PRPT doesn't render linked logo

---

src/org/pentaho/reporting/platform/plugin/ReportContentUtil.java
test-src/org/pentaho/reporting/platform/plugin/ReportContentUtilTest.java

Cherry-pick of https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/177
@pamval 
Please review.

SP-2232 - Backport of PDB-1869 - Dashboard displays a blank PIR report if it contains a Prompt with option 'Allow multiple selections' (6.0 Suite)

---

src/org/pentaho/reporting/platform/plugin/ReportContentUtil.java
test-src/org/pentaho/reporting/platform/plugin/ReportContentUtilTest.java

Cherry-pick of https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/177
@pamval 
Please review.

SP-2233 - Backport of PDB-1869 - Dashboard displays a blank PIR report if it contains a Prompt with option 'Allow multiple selections' (5.4 Suite)

---

src/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java
test-src/org/pentaho/reporting/platform/plugin/ReportingActionTest.java

@pamval, @mbatchelor, review it please. This is a backport of #174 / #181

[SP-2302] Backport of BISERVER-11556 - Scheduled PRPT doesn't render linked logo (6.0 Suite)

---

src/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java
test-src/org/pentaho/reporting/platform/plugin/ReportingActionTest.java

@pamval, @mbatchelor, review it please. This is a backport of #174 / #181

[SP-2303] Backport of BISERVER-11556 - Scheduled PRPT doesn't render linked logo (5.4 Suite)

---

package-res/reportviewer/reportviewer.js

- cherry picked implementation João (https://github.com/jvelasques/pentaho-platform-plugin-reporting/commit/c5ec4304a543046432e375750a329fdf848e467d)
- added some comments to "_getAcceptedPage" function
@jvelasques @diogofscmariano @pamval @krivera-pentaho @plagoa please review

[BACKLOG-6102] Checked setting 'accepted-page' parameter to promptPanel

---

package-res/reportviewer/reportviewer-prompt.js

[BACKLOG-6876] RV: Setup PromptAPI

---

package-res/reportviewer/messages/messages_de.properties

[BACKLOG-6892] 6.1 Localization for PUC

---

src/org/pentaho/reporting/platform/plugin/connection/messages_de.properties
src/org/pentaho/reporting/platform/plugin/connection/messages_fr.properties
src/org/pentaho/reporting/platform/plugin/connection/messages_ja.properties
src/org/pentaho/reporting/platform/plugin/messages/messages_de.properties
src/org/pentaho/reporting/platform/plugin/messages/messages_fr.properties
src/org/pentaho/reporting/platform/plugin/messages/messages_ja.properties

[BACKLOG-6892] Updating locale strings for 6.1

---

package-res/reportviewer/messages/messages.properties
package-res/reportviewer/messages/messages_de.properties
package-res/reportviewer/messages/messages_fr.properties
package-res/reportviewer/messages/messages_ja.properties
package-res/reportviewer/reportviewer-prompt.js

- Removed function getString override

[BACKLOG-6898] - Re-implement PromptPanel#getString function

---

src/org/pentaho/reporting/platform/plugin/ParameterContentGenerator.java
src/org/pentaho/reporting/platform/plugin/RenderType.java
src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java
src/org/pentaho/reporting/platform/plugin/staging/AsyncJobFileStagingHandler.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java

Fix to Instance_end to use proper status.

[BISERVER-1225] - Fix correct audit status for success async report execuiton

---

config/karma.conf.js
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
test-js/reportviewer-spec.js

- Change get promptNeeded function to use the prompting API
- Added unit tests

[BACKLOG-6860] - RV: Review promptNeeded state access

---

src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java
src/org/pentaho/reporting/platform/plugin/async/IAsyncReportListener.java
src/org/pentaho/reporting/platform/plugin/async/IAsyncReportState.java
src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
test-src/org/pentaho/reporting/platform/plugin/JobManagerTest.java

Hello,
On mockup http://jira.pentaho.com/secure/attachment/64522/biserver-1225%20ux.png
we have rows / totalRows and pages / totalPages labels.
Appropriate fields added to json.
We may consider moving totalPages to ReportProgressEvent and implementing mutation logic in AbstractReportProcessor.
@tmorgner

[BISERVER-1225] New json fields to match mockup

---

package-res/reportviewer/reportviewer.js
test-js/reportviewer-spec.js

- Removed unneeded function getAcceptedPage by using the param name "accepted-page" directly
- Updated unit tests

[BACKLOG-6760]

---

config/require-config.js
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
test-js/reportviewer-prompt-spec.js
test-js/reportviewer-spec.js
test-js/utils/registryMock.js

- Adding unit test
- Relativizing test-js paths, so test utils are properly resolved.

[BACKLOG-6961] RV: Setup getParameterDefinition usage

---

.idea/misc.xml
src/org/pentaho/reporting/platform/plugin/cache/AbstractReportContentCache.java
src/org/pentaho/reporting/platform/plugin/cache/BiPredicate.java
src/org/pentaho/reporting/platform/plugin/cache/DeleteOldOnAccessCache.java
src/org/pentaho/reporting/platform/plugin/cache/FileSystemCacheBackend.java
test-src/org/pentaho/reporting/platform/plugin/cache/FileSystemCacheBackendTest.java

[PRD-5599] Back to Java 1.7

---

config/karma.conf.js
config/require-config.js
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
test-js/reportviewer-prompt-spec.js
test-js/reportviewer-spec.js
test-js/utils/registryMock.js

Sync with master

---

package-res/reportviewer/reportviewer-prompt.js

1. Fixed wrong behavior with render mode.
Steps:
- open Inventory List report
- uncheck Auto-Submit
- select Line -> Motorcycles
- see query in console. Should be request with renderMode: PARAMETER but now we have renderMode: XML
2. Also removed unnecessary condition for inSchedulerDialog.
@pentaho/orlandocalisbon please review and merge

[BACKLOG-6961] Fixed setting renderMode for callbacks.

---

.gitignore
config/karma.ci.conf.js
config/karma.conf.js
package.json

1. Configured html coverage reporter for karma.ci.conf.js
2. Configured mocha reporter for karma.conf.js

[TEST] Changed configs for karma

---

src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java

[BACKLOG-7183] Prevent session leaks in multithread environment

---

src/org/pentaho/reporting/platform/plugin/SimpleReportingComponent.java

catch and info in case of ReportInterruptedException

[BACKLOG-6988] - put info message instead of stacktrace in case of interruption

---

package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
test-js/reportviewer-prompt-spec.js
test-js/reportviewer-spec.js

- Updated RV code to use the API prompting
- Added function to the report prompt to get state properties using the API.
- Updated the code to use this new function
- Added unit tests

[BACKLOG-6863] - RV: Review autoSubmit state access

---

src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java
test-src/org/pentaho/reporting/platform/plugin/async/TestInterruptionInterception.java
test-src/org/pentaho/reporting/platform/plugin/output/EmailOutputTest.java

[BACKLOG-7081] - remove exessive interrupt.

---

package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
test-js/reportviewer-prompt-spec.js
test-js/reportviewer-spec.js
test-js/utils/registryMock.js

[BACKLOG-6878] RV: Reviewed init usages

---

package-res/reportviewer/reportviewer.js
test-js/reportviewer-spec.js

- Changed code to call prompting API
- Added unit tests

[BACKLOG-7146] - RV: Review showParameterUI usages

---

package-res/reportviewer/reportviewer-app.js

[CLEANUP] Removed old commented code. Related with BACKLOG-5799.

---

.gitignore
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
test-js/reportviewer-prompt-spec.js
test-js/reportviewer-spec.js

need merge after pentaho/pentaho-platform-plugin-common-ui#694

[BACKLOG-6882] RV: Reviewed submit usages

---

package-res/reportviewer/reportviewer.js
test-js/reportviewer-spec.js

- added calls to the prompting API
- added unit tests

[BACKLOG-7145] - RV: Review allowAutoSubmit usages

---

package-res/plugin.spring.xml
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/JobManager.java
test-src/org/pentaho/reporting/platform/plugin/JobManagerResponseCodeTest.java

Make polling interval for async execution configurable.
@tmorgner

[BACKLOG-7306] Make polling interval configurable

---

package-res/plugin.spring.xml
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/JobManager.java

Set default to 1,5 seconds, otherwise dialog blinks.
Also switched to the default constructor in spring.
@tmorgner

[BACKLOG-7264] Added progress bar showing threshold configuration

---

package-res/reportviewer/reportviewer-prompt.js

- using "common-ui/underscore" instead of "underscore" module ID

[BACKLOG-6961] Fixed usage of underscore dependency

---

package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java
src/org/pentaho/reporting/platform/plugin/async/IAsyncReportListener.java
src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java

Cleaned up code and uplied changes to use total pages from report progress event.
Thomas, take a look please.
@tmorgner

[BACKLOG-7159] Apply code changes with total pages available

---

package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js

[BACKLOG-7404] Async mode still fires expensive pagination call

---

src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java

- do not erase report 'CANCELED' status in case of Exception

[BACKLOG-7410] - Fatal Error occurs on attempt to press Cancel button in progress bar

---

package-res/plugin.spring.xml

Thomas, take a look, please.
@tmorgner

[BACKLOG-7447] User friendly comment

---

package-res/reportviewer/report.html
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
test-js/parameterDefinition.xml
test-js/reportviewer-prompt-spec.js
test-js/reportviewer-spec.js

1. Reviewed "ready" usages
2. Wrote tests for "ready" and fixed incorrect test for events subscription
3. Fixed report.html to use api instead of directly panel object

[BACKLOG-6884] RV: Review ready usages

---

package-res/reportviewer/reportviewer.js

Thomas, please take a look.
@tmorgner

[BACKLOG-7421] Remove total pages from feedback dialog

---

src/org/pentaho/reporting/platform/plugin/JobManager.java
test-src/org/pentaho/reporting/platform/plugin/JobManagerTest.java

[BACKLOG-7169] Fix file name calculation + test

---

package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/JobManager.java
test-src/org/pentaho/reporting/platform/plugin/JobManagerTest.java

I've realised that we don't clear futures for main report generation job.
Added a clenup callback.
@tmorgner

[BACKLOG-7481] Clean leaked future

---

package-res/reportviewer/reportviewer.js

- added cancel logic if parameters changed
- prevented duplicated content call in corner case when requested page becomes available when report is finished
- removed unused 'isCanceled'
@tmorgner

[BACKLOG-7529] - Cancel running job if parameters are changed

---

src/org/pentaho/reporting/platform/plugin/JobManager.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java

[CLEAN-UP] - fix IFixedSizeStreamingContent to be used instead of InputStream

---

package-res/reportviewer/reportviewer.js

Fixed mess in dialog buttons callbacks.
@tmorgner please, take a look

[BACKLOG-6740] - Fix button callbacks

---

package-res/reportviewer/reportviewer.js

Fixed regression after merge with master
@tmorgner please, review.

[BACKLOG-7291] [BACKLOG-7688] - Fixed regression issues

---

src/org/pentaho/reporting/platform/plugin/ExecuteReportContentHandler.java
src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
src/org/pentaho/reporting/platform/plugin/ReportContentGenerator.java
src/org/pentaho/reporting/platform/plugin/RepositoryResourceData.java
src/org/pentaho/reporting/platform/plugin/SimpleReportingComponent.java
src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java
src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java
src/org/pentaho/reporting/platform/plugin/async/DelegatedListenableExecutor.java
src/org/pentaho/reporting/platform/plugin/async/SimpleDelegatedListenableFuture.java
src/org/pentaho/reporting/platform/plugin/connection/CdaPluginLocalQueryBackend.java
src/org/pentaho/reporting/platform/plugin/connection/PentahoKettleTransFromFileProducer.java
src/org/pentaho/reporting/platform/plugin/output/AbstractHtmlOutput.java
src/org/pentaho/reporting/platform/plugin/output/DefaultReportOutputHandlerFactory.java
src/org/pentaho/reporting/platform/plugin/output/ReportOutputHandlerFactory.java
src/org/pentaho/reporting/platform/plugin/output/ReportOutputHandlerSelector.java
src/org/pentaho/reporting/platform/plugin/staging/AbstractStagingHandler.java
src/org/pentaho/reporting/platform/plugin/staging/MemStagingHandler.java
src/org/pentaho/reporting/platform/plugin/staging/TempFileStagingHandler.java
src/org/pentaho/reporting/platform/plugin/staging/ThruStagingHandler.java

Fixed checkstyle issues in plugin.
@tmorgner

Checkstyle

---

package-res/reportviewer/reportviewer.js

[BACKLOG-7552] Report generation is not cancelled by closing dashboard

---

package-res/reportviewer/reportviewer.js

Moved check to the right place.

[BACKLOG-7783] - Fix progress bar not showing

---

package-res/plugin.spring.xml
package-res/reportviewer/dojo/pentaho/reportviewer/FeedbackScreen.js
package-res/reportviewer/dojo/pentaho/reportviewer/ScheduleScreen.js
package-res/reportviewer/messages/messages.properties
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/JobManager.java

Thomas, please take a look.
Please pay attention to message strings :gb: 
@tmorgner

[BACKLOG-7738] - Auto-scheduling based on report row quantity

---

package-res/reportviewer/reportviewer.js

[BACKLOG-7605] Glass pane needed when loading first page

---

test-src/org/pentaho/reporting/platform/plugin/cache/FileSystemCacheBackendTest.java

- we don't have control of execution order, let's make it more deterministic that write starts after read
@tmorgner please take look

[CLEANUP] - Fix test failing sometimes

---

package-res/reportviewer/reportviewer.js

Two issues fixed:
-  view rport button didn't work after canceling, scheduling and when report failed
-  sometimes feedback screen wasn't closed after auto-schedule

BACKLOG-7919-7920

---

package-res/plugin.spring.xml
package-res/reportviewer/paginationTemplate.html
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
resource/solution/system/reporting/reportviewer/paginationTemplate.html
src/org/pentaho/reporting/platform/plugin/JobManager.java
src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java
src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java
src/org/pentaho/reporting/platform/plugin/async/IAsyncReportExecution.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java
src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
src/org/pentaho/reporting/platform/plugin/output/PaginationControlWrapper.java
test-src/org/pentaho/reporting/platform/plugin/PageableHTMLTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionAuditTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionInterruptTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
test-src/org/pentaho/reporting/platform/plugin/async/TestListener.java

Hello @tmorgner, I have a couple of thingth for review:
1. Clean futures and tasks in a proper way
2. Move auto-scheduling to server side
3. Implement simple UI to view large paginated reports without hanging a browser (see video)
https://drive.google.com/file/d/0BzVckAbDytTXNU5FOXNqODJFVWM/view

Backlog 7929

---

package-res/reportviewer/dojo/pentaho/reportviewer/FeedbackScreen.js

[CLEANUP] - Fix FeedbackScreen.js format to fix build

---

package-res/reportviewer/dojo/pentaho/reportviewer/FeedbackScreen.js
package-res/reportviewer/reportviewer-prompt.js

[CLEANUP] - Fix phantom js tests

---

src/org/pentaho/reporting/platform/plugin/staging/AsyncJobFileStagingHandler.java

@tmorgner @pamval  please merge

[CLEANUP] - Unused imports

---

test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionAuditTest.java

@tmorgner fixed naughty test
Interesting lines 160-162 and 179-182.

[CLEANUP] - Fix race condition in naughty test

---

package-res/reportviewer/paginationTemplate.html

Please [see](https://www.dropbox.com/s/dafgqr0h6e8owxp/Screenshot%202016-05-03%2012.41.22.png?dl=0) how does it look like. I intentionally did not use the one we already have, to avoid including js and css for it.
@tmorgner @kcruzada

[BACKLOG-7811] - Make UI more consistent with platform page control

---

src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionInterruptTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java

[CLEANUP] - Check constructor parameters for null and fix tests

---

package-res/reportviewer/reportviewer.js

[BACKLOG-8154] - Don't update page count for output types != HTML

---

package-res/reportviewer/reportviewer.js

[BACKLOG-8074] - Cancel old job if output type changed

---

src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
src/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutput.java
test-src/org/pentaho/reporting/platform/plugin/PageableHTMLTest.java

- pulled up methods to PageableHtmlOutput
- added scheduling branch to generate() method
- updated tests

[BACKLOG-8261] - Write all pages for scheduled non-cacheable HTML

---

src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java
test-src/org/pentaho/reporting/platform/plugin/JobManagerTest.java
test-src/org/pentaho/reporting/platform/plugin/PageableHTMLIT.java
test-src/org/pentaho/reporting/platform/plugin/PageableHTMLTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
test-src/org/pentaho/reporting/platform/plugin/async/WriteToJcrTaskTest.java
test-src/org/pentaho/reporting/platform/plugin/output/AbstractHTMLOutputTest.java
test-src/org/pentaho/reporting/platform/plugin/output/DefaultReportOutputHandlerFactoryTest.java
test-src/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutputTest.java

[CLEANUP] - Improve code coverage

---

package-res/reportviewer/reportviewer.js

Hello Thomas,
We faced common JS issue when you fix something and another part breaks ( may be we need to write JS tests too?).
I refactored async logic in js to make it more maintainable, also added comments to make it more clear what is happening.
While doing it I also fixed a couple of bugs :)
[BACKLOG-8100] - Page loading notification is displayed after cancellation
of report
[BACKLOG-8072] - Page caching counter displays above glass pane
if requested not-cached page
[BACKLOG-8097] - Report is downloaded twice
when changing parameters of report
[BACKLOG-8098] - Report is downloaded
when changing output type though Auto-submit is unchecked
I tested it manually and we will have a couple of days before merge to master for QA team to test it too.
Please take a look.
@tmorgner

[CLEANUP] - Make async logic in JS more documented and clean

---

package-res/reportviewer/dojo/pentaho/reportviewer/FeedbackScreen.html
package-res/reportviewer/reportviewer.css
package-res/reportviewer/themes/crystal/Crystal.css
package-res/reportviewer/themes/onyx/Onyx.css

[BACKLOG-8086] Fix styling for Onyx for the progress bar dialog

---

package-res/reportviewer/paginationTemplate.html
resource/solution/system/reporting/reportviewer/paginationTemplate.html
test-src/org/pentaho/reporting/platform/plugin/PageableHTMLTest.java

[BACKLOG-8361] - Unable to navigate to the last page of saved in HTML report

---

src/org/pentaho/reporting/platform/plugin/async/AsyncSystemListener.java
src/org/pentaho/reporting/platform/plugin/async/AutoScheduleListener.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java
src/org/pentaho/reporting/platform/plugin/cache/DeleteOldOnAccessCache.java
src/org/pentaho/reporting/platform/plugin/cache/IReportContentCache.java
src/org/pentaho/reporting/platform/plugin/cache/PluginSessionCache.java
src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncIT.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncSystemListenerIT.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncSystemListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AutoScheduleListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/cache/DeleteOldOnAccessCacheTest.java
test-src/org/pentaho/reporting/platform/plugin/cache/PluginSessionCacheTest.java
test-src/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutputTest.java

[CLEANUP] - Cleanup cache files when platform stops

---

src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
test-src/org/pentaho/reporting/platform/plugin/JaxRsServerProvider.java
test-src/org/pentaho/reporting/platform/plugin/PageableHTMLIT.java
test-src/org/pentaho/reporting/platform/plugin/PageableHTMLTest.java
test-src/org/pentaho/reporting/platform/plugin/ParameterIT.java
test-src/org/pentaho/reporting/platform/plugin/PentahoReportEnvironmentTest.java
test-src/org/pentaho/reporting/platform/plugin/Prd5659IT.java
test-src/org/pentaho/reporting/platform/plugin/ReportingActionIT.java
test-src/org/pentaho/reporting/platform/plugin/ReportingComponentIntegrationIT.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncIT.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncSystemListenerIT.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncSystemListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/ISchedulingDirectoryStrategyTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionInterruptTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
test-src/org/pentaho/reporting/platform/plugin/output/EmailOutputTest.java
test-src/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutputTest.java
test-src/org/pentaho/reporting/platform/plugin/output/PaginationControlWrapperTest.java
test-src/org/pentaho/reporting/platform/plugin/repository/ReportContentLocationIT.java
test-src/org/pentaho/reporting/platform/plugin/staging/AbstractStagingHandlerTest.java
test-src/org/pentaho/reporting/platform/plugin/staging/TempFileStagingTest.java

Separate PR for 8579 with all tests.

[BACKLOG-8579] - Fix scheduling for partially saved reports

---

package-res/reportviewer/reportviewer.js

Reverts pentaho/pentaho-platform-plugin-reporting#363
@tmorgner 
Please review.

Revert "[BACKLOG-8423] Cancel request is sent only once if dashboard mode is …"

---

.idea/misc.xml

Just in order not to switch it each time as far as sources are already 1.8
@tmorgner

[CLEANUP] - Update IDEA project JDK to 1.8

---

src/org/pentaho/reporting/platform/plugin/JobManager.java

- use polymorfic getExecutor method to get executor from the desired context
@tmorgner this kind of bugs could only be cacthed before manual testing if we have integration tests for the whole platform :(

BACKLOG-8976 - Async jobs fail with 404 in PIR

---

package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
package-res/reportviewer/themes/crystal/Crystal.css
package-res/reportviewer/themes/onyx/Onyx.css

[BACKLOG-8335] Fix styling for the error message dialog in Onyx theme

---

package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/JobManager.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java
src/org/pentaho/reporting/platform/plugin/messages/messages.properties
src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
src/org/pentaho/reporting/platform/plugin/output/DefaultReportOutputHandlerFactory.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
test-src/org/pentaho/reporting/platform/plugin/async/TriggerScheduledContentWritingHandlerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/WriteToJcrTaskTest.java
test-src/org/pentaho/reporting/platform/plugin/output/DefaultReportOutputHandlerFactoryTest.java
test-src/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutputTest.java
test-src/org/pentaho/reporting/platform/plugin/repository/ReportContentLocationTest.java

BACKLOG-8067 - Add HTML email output type

---

src/org/pentaho/reporting/platform/plugin/messages/messages.properties

BACKLOG-8067 - Proper label text for email output

---

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

Provide better parameter handling to avoid multiple posts
to the server for revalidations.
Added new methods to discover cascading parameters as far as write this
info in responce xml.

[BACKLOG-7980] - parameter dependencies server side discovery func.

---

package-res/plugin.spring.xml

@tmorgner now PentahoSystem resolves it and spring config works

CLEANUP - Make spring configuration work for  ReportOutputHandlerFactory

---

src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java

[CLEANUP] - Remove unused method.
@tmorgner 
Please review.

[CLEANUP] - Remove unused method.

---

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
src/org/pentaho/reporting/platform/plugin/ReportContentUtil.java
test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

added new attributes to mark dependent parametes
rebased #397 
@tmorgner

BACKLOG-7980 - attribute for dependent parametes

---

package-res/plugin.spring.xml
package-res/reportviewer/dojo/pentaho/reportviewer/SuccessScheduleScreen.js
package-res/reportviewer/messages/messages.properties
package-res/reportviewer/report.html
package-res/reportviewer/reportviewer-main-module.js
package-res/reportviewer/reportviewer-prompt.js
package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/JobManager.java
src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java
src/org/pentaho/reporting/platform/plugin/async/AsyncExecutionStatus.java
src/org/pentaho/reporting/platform/plugin/async/AutoScheduleListener.java
src/org/pentaho/reporting/platform/plugin/async/IAsyncReportExecution.java
src/org/pentaho/reporting/platform/plugin/async/IPentahoAsyncExecutor.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java
src/org/pentaho/reporting/platform/plugin/async/UpdateSchedulingLocationListener.java
test-src/org/pentaho/reporting/platform/plugin/BackgroundJobContentGeneratorTest.java
test-src/org/pentaho/reporting/platform/plugin/JobManagerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncIT.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AutoScheduleListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
test-src/org/pentaho/reporting/platform/plugin/async/UpdateSchedulingLocationListenerTest.java
test-src/org/pentaho/reporting/platform/plugin/cache/DefaultReportCacheIT.java

@tmorgner please review, junits are on the way

BACKLOG-7817 - Location prompting in reportviewer tab

---

package-res/plugin.spring.xml

[BACKLOG-7817] - Enable file location prompting by default

---

package-res/reportviewer/messages/messages_es.properties
src/org/pentaho/reporting/platform/plugin/connection/messages_es.properties
src/org/pentaho/reporting/platform/plugin/messages/messages_es.properties

Hi all,
I've translated the strings in the messages.properties files of this project. It'd be great if we could count on these translations being available in future releases.
Regards,
Antonio

Add Spanish translations

---

src/org/pentaho/reporting/platform/plugin/output/EmailOutput.java
test-src/org/pentaho/reporting/platform/plugin/output/EmailOutputTest.java

@tmorgner It works. The only concern I have - it can affect another reports running at the same time.

[BACKLOG-9898] - Force styles inlining for HTML (E-Mail) output

---

ivy.xml
package-res/plugin.spring.xml
package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/BackgroundJobReportContentGenerator.java
src/org/pentaho/reporting/platform/plugin/JobManager.java
src/org/pentaho/reporting/platform/plugin/async/IJobIdGenerator.java
src/org/pentaho/reporting/platform/plugin/async/IPentahoAsyncExecutor.java
src/org/pentaho/reporting/platform/plugin/async/JobIdGenerator.java
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java
test-src/org/pentaho/reporting/platform/plugin/BackgroundJobContentGeneratorTest.java
test-src/org/pentaho/reporting/platform/plugin/JobManagerTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncIT.java
test-src/org/pentaho/reporting/platform/plugin/async/JobIdGeneratorTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
test-src/org/pentaho/reporting/platform/plugin/async/ReservedIdIT.java

BACKLOG-9160 - Pre-generate async jobs ids

---

package-res/plugin.spring.xml
package-res/reportviewer/report.html
package-res/reportviewer/reportviewer.js
src/org/pentaho/reporting/platform/plugin/CacheManagerEndpoint.java
test-src/org/pentaho/reporting/platform/plugin/CacheManagerEndpointTest.java
test-src/org/pentaho/reporting/platform/plugin/async/AsyncIT.java
test-src/org/pentaho/reporting/platform/plugin/async/LocationPromptingIT.java

[BACKLOG-9595] - Clear cache from the reportviewer navigation panel

---

package-res/plugin.spring.xml
src/org/pentaho/reporting/platform/plugin/async/ClearCacheAction.java
test-src/org/pentaho/reporting/platform/plugin/async/ClearCacheActionTest.java

[BACKLOG-10020] - Clear cache action

---

src/org/pentaho/reporting/platform/plugin/PentahoPlatformModule.java
src/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java
src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
src/org/pentaho/reporting/platform/plugin/output/EmailOutput.java
src/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutput.java
test-src/org/pentaho/reporting/platform/plugin/SimpleReportingActionTest.java
test-src/org/pentaho/reporting/platform/plugin/output/EmailOutputTest.java

[BACKLOG-10063] - Support pageable HTML in platform scheduler

---

package-res/reportviewer/report.html
package-res/reportviewer/reportviewer.css

[BACKLOG-9595]-Button styles

---

package-res/reportviewer/reportviewer.js

Add a check for mobile device case.

[BACKLOG-9595]-Fix crash on iPad

---

package-res/reportviewer/report.html
package-res/reportviewer/reportviewer.css

[BACKLOG-10292]-Fix refresh button styles

---

package-res/reportviewer/paginationTemplate.html

Double check for better consistency.

[backlog-8362] - enchase caclulation of frame scrollWidth/Height

---

package-res/reportviewer/reportviewer-prompt.js
src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

Depends on https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/828

[BACKLOG-8607]-Send minimized parameters response from server

---

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java

[BACKLOG-10689] - Report could be executed with not valid parameters.

[BACKLOG-10689] - Report could be executed with not valid parameters.

---

src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java

[BACKLOG-11174]-Avoid race condition

---

package-res/reportviewer/reportviewer.js

Let's make reporting on iPad great again

[BACKLOG-11523]-Fix crashes on iPad

---

package-res/settings.xml

Most issues are resolved. Time to enable the feature.
@tmorgner please merge

[BACKLOG-6859]-Enable row limit ui by default

---

package-res/reportviewer/reportviewer.js

[BACKLOG-11576]-Don't show 'Run in background' button on mobile

---

ivy.xml
test-src/org/pentaho/reporting/platform/plugin/async/ExecutorIT.java

Just found that one of the tests was ignored after the Spring version update.
As far as we don't have Spring 2 in the final build, I believe it's preety safe.
@tmorgner

[CLEANUP]-Bring the ignored test back to it's duties

---

package-res/reportviewer/themes/sapphire/Sapphire.css

[BACKLOG-11904]-Content table style fix

---

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java

[PRD-3883]-Support DRILLDOWN links from ChartExpressions

---

src/org/pentaho/reporting/platform/plugin/BackgroundJobReportContentGenerator.java
test-src/org/pentaho/reporting/platform/plugin/BackgroundJobContentGeneratorTest.java

[BACKLOG-11984]-Get context path from HttpRequest

---

package-res/reportviewer/reportviewer.js

Flag was overriden by the canceled job while the new job was in progress.
@tmorgner @pamval @kcruzada

[BACKLOG-12009]-Set 'finished' immediately, not on status

---

src/org/pentaho/reporting/platform/plugin/CacheManagerEndpoint.java
src/org/pentaho/reporting/platform/plugin/cache/DeleteOldOnAccessCache.java
src/org/pentaho/reporting/platform/plugin/cache/IReportContentCache.java
src/org/pentaho/reporting/platform/plugin/cache/PentahoDataCache.java
src/org/pentaho/reporting/platform/plugin/cache/PluginSessionCache.java
test-src/org/pentaho/reporting/platform/plugin/CacheManagerEndpointTest.java
test-src/org/pentaho/reporting/platform/plugin/cache/DeleteOldOnAccessCacheTest.java

@tmorgner could you please review

[BACKLOG-12100]-Clear cache for the current user only

---

package-res/plugin.spring.xml
src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionAuditTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java

Sorry for ignored tests - I fixed some bot others are not so trivial.
@pamval @tmorgner @kcruzada @CodeOnCoffee

[BACKLOG-12120]-Run async jobs with runAsAdmin

---

src/org/pentaho/reporting/platform/plugin/output/FastCSVOutput.java
test-src/org/pentaho/reporting/platform/plugin/output/FastCSVOutputTest.java

Epic bug that should be caught by tests.
Fixed it and updated tests to touch fast mode logic.
@tmorgner

[BACKLOG-12234]-Fix fast csv output + tests

---

test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionAuditTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java
test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoMondrianConnectionProviderTest.java

We commented out a couple of tests while hacking for the release build.
Bringing them back.
@tmorgner

[CLEANUP]-Make async tests great again

---

package-res/reportviewer/report.html

[BACKLOG-11526] - An arrow is absent on Row Limit drop-down.

[BACKLOG-11526] - An arrow is absent on Row Limit drop-down.

---

package-res/reportviewer/report.html

Reverts pentaho/pentaho-platform-plugin-reporting#502

Revert "Backport of [BACKLOG-11526] - An arrow is absent on Row Limit drop-down."

---

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

BISERVER-13435 Cascading parameter retains old values and shows key-value from old values

---

src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConnectionProvider.java
src/org/pentaho/reporting/platform/plugin/connection/PentahoPoolDataSourceConnectionProvider.java
src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java
test-src/org/pentaho/reporting/platform/plugin/async/ExecutionRestartTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConnectionProviderTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPoolDataSourceConnectionProviderTest.java
test-src/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutputTest.java

- added receiving connection from PoolingDataSource
- added unit tests

[BISERVER-13407]-ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

---

src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConnectionProvider.java
src/org/pentaho/reporting/platform/plugin/connection/PentahoPoolDataSourceConnectionProvider.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConnectionProviderTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPoolDataSourceConnectionProviderTest.java

- added receiving connection from PoolingDataSource
- added unit tests

[SP-3102][BISERVER-13407]-ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

---

src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConnectionProvider.java
src/org/pentaho/reporting/platform/plugin/connection/PentahoPoolDataSourceConnectionProvider.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConnectionProviderTest.java
test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPoolDataSourceConnectionProviderTest.java

- added receiving connection from PoolingDataSource
- added unit tests

[SP-3101][7.0.0.2][BISERVER-13407]-ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

---

ivy.xml

only merge after https://github.com/pedrofvteixeira/pentaho-platform/tree/BACKLOG-12101 merge

[BACKLOG-12101] Refactors pentaho-platform test dependencies to Maven

---

test-src/org/pentaho/reporting/platform/plugin/connection/PentahoPmdConnectionProviderTest.java

[CLEANUP] fixed checkstyle violations

---

package-res/reportviewer/reportviewer.js

* The issue is reproduced only in IE11 and PDF Output
* onLoad event is not triggered when hidden form is submitted to iframe
* Using  "onreadystatechange" <iframe> attribute to trigger the event

[BISERVER-12804] PDF-Output is not shown in PUC 5.2 in Internet Explorer

---

package-res/reportviewer/reportviewer.js

Depends on 
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/510
https://github.com/pentaho/pentaho-platform/pull/3365
https://github.com/pentaho/data-access/pull/834

[PPP-3410]-Avoid memory leaks

---

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

[SP-3177][BACKLOG-14580]-Don't reset selection on the report opening

---

test-src/org/pentaho/reporting/platform/plugin/MockUserDetailsService.java

Devci is failing on master branch since Monday because of this.

[CLEANUP]-Fix a compile error on a devci

---

config/context.js
config/karma.ci.conf.js
config/karma.conf.js
config/require-config.js
package.json
test-js/sorry-notests-spec.js

[CLEANUP]-Empty JS test suite to avoid Wingman errors

---

package-res/reportviewer/reportviewer.js

#518 + #543 + top/parent calls are still secured

[SP-3339][PPP-3410]-Avoid memory leak

---

core/src/main/javascript/reportviewer/reportviewer.js

A typo which caused BACKLOG-15739
@annapopova1 FYI

[PPP-3410]-Fix a typo, which prevented removing a listener in dashboards

---

core/src/main/javascript/reportviewer/reportviewer-timeutil.js

[PRD-5879] Datepicker doesn't display a user selection if a date has a 30/45 minute time zone

---

pom.xml

DO NOT MERGE prior to merge of kettle mavenization!

[BACKLOG-12995] Adding jersey exclusion

---

core/src/main/java/org/pentaho/reporting/platform/plugin/PentahoReportEnvironment.java
core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java
core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingComponent.java
core/src/test/java/org/pentaho/reporting/platform/plugin/PentahoReportEnvironmentTest.java

[BISERVER-12968]-Self Links defined in a PRPT chart do not work on the

---

core/src/test/config/javascript/karma.ci.conf.js
core/src/test/config/javascript/karma.conf.js
core/src/test/javascript/reportviewer-prompt-spec.js

- added missing mocked dependencies
- reviewed karma configuration files

[TEST] fix broken tests

---

core/src/main/javascript/reportviewer/reportviewer.css

[BACKLOG-18122] - PIR: Update colors and icons for the Ruby theme

---

core/src/main/javascript/reportviewer/themes/ruby/Ruby.css

[BACKLOG-19028] Make Ruby progress bar equal in PIR and Reporting

---

core/src/main/javascript/reportviewer/reportviewer-prompt.js

The problem arises on changing value in data-picker parameter at the certain conditions:
1)Parameter has data-format;
2)Parameter has post-processor-formula;
3)Post-processor-formula generates the date in the format that differs from data-format;
Parameter xml generated for Report Viewer contains date in the internal transport format (ISO-8601) used by Pentaho Reporting Engine.
But also parameter can contain its own data-format.
We need to convert dates from/to these formats to compare them correctly.
Now we do not do this one.
That is why on comparying "old" and "new" data in the function _compareDatesOnly we compare two different dates in fact .
And of course they are not equall and we try to set up the "new" value again and again.
The fix is to apply parameter's defined format and the …

[BISERVER-13685]: The certain report with Post Processing Formulas and data pickers goes into a loop and it never stops

---

core/src/main/javascript/reportviewer/reportviewer.js

Reverts pentaho/pentaho-platform-plugin-reporting#590

Revert "[SP-3785]-Backport of [BISERVER-13694]-Report Progress Viewer's "Run …"

---

core/src/main/config/javascript/build.js

- css file was excluded due to the load issues

[PRD-5915] 404 opensans-regular font not found error when running prpt report in 7.1

---

core/src/main/config/javascript/build.js

[SP-3823] Backport of PRD-5915 - 404 opensans-regular font not found error when running prpt report in 7.1 (7.1 Suite)

---

license/templates/licenseHeader.txt

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

---

core/pom.xml
core/src/main/resources/org/pentaho/reporting/platform/plugin/module.properties
pom.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-1757] version name consolidation

---

core/pom.xml
pom.xml

Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/649

[BACKLOG-20163] Update downstreams

---

core/src/main/javascript/reportviewer/reportviewer.js

[BISERVER-13735] Run in Background Dialog should not be shown when PRPT and PRPTI reports are being used on a Dashboard

---

core/src/main/java/org/pentaho/reporting/platform/plugin/drilldown/ContentLinkFunction.java
core/src/test/java/org/pentaho/reporting/platform/plugin/drilldown/ContentLinkFunctionTest.java

using content linking from PRPT on a Dashboard

[BISERVER-13895]-Cannot read property 'fireOutputParam' of undefined when

---

core/src/main/java/org/pentaho/reporting/platform/plugin/drilldown/ContentLinkFunction.java
core/src/test/java/org/pentaho/reporting/platform/plugin/drilldown/ContentLinkFunctionTest.java

[SP-4269][BISERVER-13895]-Cannot read property 'fireOutputParam' of undefined when
using content linking from PRPT on a Dashboard
@pentaho-lmartins, @mchen-len-son, could you please take a look?

[SP-4269][BISERVER-13895]-Cannot read property 'fireOutputParam' of undefined when

---

core/pom.xml
core/src/main/config/javascript/build.js
core/src/main/config/javascript/context.js
core/src/test/config/javascript/context.js
package-lock.json

@pentaho/millenniumfalcon please review.
Depends on pentaho/pentaho-platform-plugin-common-ui#1295.

[BACKLOG-23466] Refactor VizAPI module system.

---

core/src/main/resources/org/pentaho/reporting/platform/plugin/connection/messages_zh_CN.properties
core/src/main/resources/org/pentaho/reporting/platform/plugin/messages/messages_zh_CN.properties

@pentaho/millenniumfalcon please review

[BACKLOG-25043] Simplified Chinese localization

---

core/pom.xml

@pentaho/x-wing @pedrofvteixeira @graimundo

[CLEANUP] Fix missing jaxen dependency causing test failures

---

core/src/main/config/javascript/build.js
core/src/main/javascript/reportviewer/unittests/TestRunner.html
core/src/main/javascript/reportviewer/unittests/reportviewer-formatting-tests.js
core/src/main/javascript/reportviewer/unittests/reportviewer-tests.js

@pentaho/millenniumfalcon please review

[BACKLOG-17305] Removed references to pen.require and pen.define

---

core/src/main/java/org/pentaho/reporting/platform/plugin/StagingHandler.java
core/src/main/java/org/pentaho/reporting/platform/plugin/staging/TempFileStagingHandler.java
core/src/test/java/org/pentaho/reporting/platform/plugin/StagingHandlerTest.java
core/src/test/java/org/pentaho/reporting/platform/plugin/staging/TempFileStagingTest.java

[PRD-5902] Reporting plugin uses different code paths for tests

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java

[SP-4855] [BISERVER-14069] - Fixed Language Translation Properties Files Not Pi…
@ssamora @LeonardoCoelho71950 please review

[SP-4855] - Backport of BISERVER-14069 - Language Translation Properties Files Not Picked up from PRPTs when running on Server (8.2 Suite)

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java

[SP-4854] [BISERVER-14069] - Fixed Language Translation Properties Files Not Pi…
@ssamora @LeonardoCoelho71950 please review

[SP-4854] - Backport of BISERVER-14069 - Language Translation Properties Files Not Picked up from PRPTs when running on Server (7.1 Suite)

---

core/pom.xml
core/src/test/java/org/pentaho/reporting/platform/plugin/JobManagerTest.java
pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/109.
@graimundo

[BACKLOG-27565] Centralize CXF dependency version

---

core/pom.xml
pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/111
@graimundo

[BACKLOG-27566] Remove unneeded SLF4J dependency

---

core/pom.xml
pom.xml

@graimundo 
CC: @jmcrfp @pentaho-lmartins

[PPP-4223] - Adding missing dependency that fixes IT testing

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java

Reverts pentaho/pentaho-platform-plugin-reporting#703

Revert "[SP-5001] [BISERVER-13967] - Fixed Performance Metrics Logging for pr…"

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java

Reverts pentaho/pentaho-platform-plugin-reporting#704

Revert "[SP-5002] [BISERVER-13967] - Fixed Performance Metrics Logging for pr…"

---

core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java

[SP-5002] [BISERVER-13967] - Fixed Performance Metrics Logging for prpt run in background

---

core/src/main/javascript/reportviewer/reportviewer-app.js

@pentaho-lmartins @dcleao 
please review

[PPP-4008] - Fix calls to discontinued functions/properties

---

core/pom.xml

@ssamora 
* [BISERVER-14306] Changing order of karma testing plugin and adding a phase, fixing issue with compressed folder being made too late.

[BISERVER-14306] Multi Value List parameter values are reset after changing output type in a prpt report

---

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
core/src/main/java/org/pentaho/reporting/platform/plugin/ReportContentUtil.java
core/src/test/java/org/pentaho/reporting/platform/plugin/ReportContentUtilTest.java

Reverts pentaho/pentaho-platform-plugin-reporting#732

Revert " [PRD-6070] Date Picker showing incorrect value when client is in different day due to Timezone difference"

---

core/src/main/javascript/reportviewer/messages/messages_de.properties
core/src/main/javascript/reportviewer/messages/messages_fr.properties
core/src/main/javascript/reportviewer/messages/messages_ja.properties
core/src/main/javascript/reportviewer/messages/messages_zh_CN.properties

(cherry picked from commit 6f25c8a9b799255c2118b0b0a474d928da7d95e8)

[BACKLOG-33112] - Updated translations for 9.0

---

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
core/src/test/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

@ssamora 
@ppatricio 
@smmribeiro

[PPP-4514] - Insecure Code: ParameterXmlContentHandler:1051

---

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
core/src/test/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

@ssamora 
@ppatricio 
@smmribeiro

[SP-5688] - Backport of PPP-4514 - Insecure Code: ParameterXmlContentHandler:1051 (8.3 Suite)

---

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
core/src/test/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java

@ssamora 
@ppatricio 
@smmribeiro

[SP-5689] - Backport of PPP-4514 - Insecure Code: ParameterXmlContentHandler:1051 (9.0 Suite)

---

core/src/main/javascript/reportviewer/reportviewer.js
core/src/test/javascript/reportviewer-spec.js

@ssamora 
@smmribeiro 
@dcleao

[BISERVER-14512] - Text box values are only displayed for about a second in prpt reports published to PUC

---

core/src/main/javascript/reportviewer/reportviewer.js
core/src/test/javascript/reportviewer-spec.js

[SP-5847] - Backport of BISERVER-14512 - Text box values are only displayed for about a second in prpt reports published to PUC (8.3 Suite)

---

core/src/main/javascript/reportviewer/reportviewer.js
core/src/test/javascript/reportviewer-spec.js

[SP-5848] - Backport of BISERVER-14512 - Text box values are only displayed for about a second in prpt reports published to PUC (9.1 Suite)

---

core/src/main/javascript/reportviewer/reportviewer-prompt.js
core/src/test/javascript/reportviewer-prompt-spec.js

@bcostahitachivantara 
@smmribeiro 
@ssamora

[BISERVER-14641] Infinite loop in PUC when using Now() function on Parameter's POST Processing formula with specific Timezone in Server - Client

---

core/src/main/java/org/pentaho/reporting/platform/plugin/cache/FileSystemCacheBackend.java
core/src/test/java/org/pentaho/reporting/platform/plugin/cache/FileSystemCacheBackendTest.java

@smmribeiro @bcostahitachivantara

[PDI-19188] Memory leak at Pentaho server logout.

---

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterContentGenerator.java
core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
core/src/main/java/org/pentaho/reporting/platform/plugin/ReportContentUtil.java
core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java
core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingComponent.java
core/src/test/java/org/pentaho/reporting/platform/plugin/ReportContentUtilTest.java

[BACKLOG-38811] Update code to provide more options for subclassing and

---

core/src/main/javascript/reportviewer/report.html
core/src/main/javascript/reportviewer/reportviewer.js

@dcleao , @soagarwal1 , @NJtwentyone  , @singletonc  Please review this PR as part of https://hv-eng.atlassian.net/browse/BACKLOG-38613

[BACKLOG-38613] (10.1) - Options to enable the export option for PIR and PRD reports from a Dashboard

---

core/src/main/javascript/reportviewer/themes/ruby/Ruby.css

[BACKLOG-38945] CSS fix to enclose view report button in focus ring

---

core/src/main/javascript/reportviewer/report.html
core/src/main/javascript/reportviewer/reportviewer.js

[BACKLOG-38946][BACKLOG-38666] Fixed Tab order for toolbar elements

---

core/src/test/java/org/pentaho/reporting/platform/plugin/MockTableModel.java
pom.xml

[PPP-4936]-Vulnerable Component -Guava
[PPP-4936]: https://hv-eng.atlassian.net/browse/PPP-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4936]-Vulnerable Component -Guava

---

core/src/main/javascript/reportviewer/report.html
core/src/main/javascript/reportviewer/reportviewer.css

cut off when rendered in an iframe.

[BACKLOG-39139] Fix css overflow behavior to prevent content from being

---

core/src/test/java/org/pentaho/reporting/platform/plugin/MockTableModel.java
pom.xml

[PPP-4936]-Vulnerable Component :Guava
[PPP-4936]: https://hv-eng.atlassian.net/browse/PPP-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4936]-Vulnerable Component :Guava

---

core/src/main/javascript/reportviewer/report.html
core/src/main/javascript/reportviewer/reportviewer.js

Cherry picked https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/817 back to master.

[BACKLOG-38946] Add import statement and class for image styling

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XLSXOutput.java

Reverts pentaho/pentaho-platform-plugin-reporting#831
@renato-s @andreramos89

Revert "[BISERVER-14865] - Impossible to download PIR reports onto Excel 2007 format once data is past Excel limitations"

---

core/src/main/javascript/reportviewer/report.html
core/src/main/javascript/reportviewer/reportviewer.css

Cherry-pick https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/832

[BACKLOG-39835] Add an attribute for toolbar improvement

---

pom.xml

Conflicting with the property in the parent poms https://github.com/pentaho/maven-parent-poms/blob/c711c2445ca8ab5d06cec93f7936c12328855672/pom.xml#L106

[CLEANUP] - Conflicting version property

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XLSXOutput.java

[BISERVER-14865] - Impossible to download PIR reports onto Excel 2007 format once data is past Excel limitations (#831)

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/EmailOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastCSVOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamHtmlOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamJcrHtmlOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/OutputUtils.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PDFOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PNGOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PlainTextOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/RTFOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlPageableOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlTableOutput.java
core/src/test/java/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListenerTest.java

[PIR-1517] - Add a new export query limit property to the Settings file

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XLSXOutput.java

Original PR:
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/836

[SP-6489] - Backport of BISERVER-14865 - Impossible to download PIR reports onto Excel 2007 format once data is past Excel limitations (9.3 Suite)

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/EmailOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastCSVOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamHtmlOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamJcrHtmlOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/OutputUtils.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PDFOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PNGOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PlainTextOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/RTFOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlPageableOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlTableOutput.java
core/src/test/java/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListenerTest.java

Original PR:
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/843

[SP-6494] - Backport of PIR-1517 - Add a new export query limit property to the Settings file (9.3 Suite)

---

core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java

@pentaho/hoth Please review
Part of PR set 
https://github.com/pentaho/pentaho-scheduler-plugin/pull/179
https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/244
https://github.com/pentaho/pentaho-reporting/pull/1657

[BACKLOG-39678] - Schedule Output Perspective : Improve reporting engine to generate in line style and images for html rendering

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/EmailOutput.java

[BACKLOG-41287]-Updating code to match with the master code
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41287]-Updating code to match with the master code

---

core/src/main/java/org/pentaho/reporting/platform/plugin/cache/DefaultReportCache.java

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

---

core/src/main/java/org/pentaho/reporting/platform/plugin/output/EmailOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastCSVOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamHtmlOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamJcrHtmlOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/OutputUtils.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PDFOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PNGOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/PlainTextOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/RTFOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlPageableOutput.java
core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlTableOutput.java

Original PRs:
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/881
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/883
@pentaho/tatooine_dev

[SP-6753] Backport of PRD-6173 - RowLimit while exporting Excel for PRD report is not working in PUC (10.2 Suite)

---

core/src/main/javascript/reportviewer/dojo/pentaho/reportviewer/GlassPane.js
core/src/main/javascript/reportviewer/reportviewer.js

[PPP-5353]-XSS Findings For Pentaho-platform-plugin-reporting
[PPP-5353]: https://hv-eng.atlassian.net/browse/PPP-5353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5353]-XSS Findings For Pentaho-platform-plugin-reporting

---

.gitignore
core/pom.xml
package-lock.json
package.json
pom.xml

@pentaho/millenniumfalcon please review

fix: vulnerable component requirejs [PPP-5516]

---

core/src/test/java/org/pentaho/reporting/platform/plugin/JobManagerResponseCodeTest.java
core/src/test/java/org/pentaho/reporting/platform/plugin/JobManagerTest.java

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation
[BACKLOG-43098]: https://hv-eng.atlassian.net/browse/BACKLOG-43098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation

---

.eslintignore
.eslintrc.json
.gitignore
.prettierignore
.prettierrc
.puppeteerrc.js
README.MD
core/pom.xml
core/src/main/config/javascript/build.js
core/src/main/javascript/reportviewer/reportviewer.js
core/src/test/config/javascript/karma.ci.conf.js
core/src/test/config/javascript/karma.conf.js
core/src/test/config/javascript/karma.headless.conf.js
core/src/test/javascript/reportviewer-prompt-spec.js
package-lock.json
package.json
pom.xml

@pentaho/millenniumfalcon please review
This PR must be squashed

[SP-6819] Backport of PPP-5516 - Vulnerable Component: requirejs 2.3.6 (10.2 Suite)

---

core/src/main/javascript/reportviewer/reportviewer-prompt.js
core/src/test/javascript/reportviewer-prompt-spec.js
core/src/test/javascript/reportviewer-spec.js

Add TimePicker triggered by DisplayTime checkbox

[PRD-2777]-As a report designer, I want my end user as part of the date selection control to select time as well when running reports on the server
