pentaho/pentaho-platform-plugin-reporting

src/org/pentaho/reporting/platform/plugin/ParameterContentGenerator.java
The content generator instances were hanging onto stale versions of member variables (from previous executions) and the incorrect information was being used (like request parameters and report definitions) that did not apply.
=> [BACKLOG-3310] - (Using BISERVER-6.0-SNAPSHOT) Error opening Interaive report

package-res/reportviewer/reportviewer-prompt.js, package-res/reportviewer/reportviewer.js
1. Replace using Dashboards to dashboard object from panel.
2. Remove parser.parse(); to avoid error in console: "dojo/parser::parse() error Error: Tried to register widget with id==glassPane but that id is already registered".
3. Replace using pentaho.common.Messages to already defined module.
@diogofscmariano @krivera-pentaho @scottyaslan @rfellows @plagoa please review.
=> [BACKLOG-4066] Fix using Dashboards object

package-res/reportviewer/reportviewer-prompt.js
- Reviewed the formatter util usage across the components and PromptPanel. To allow component reuse across pentaho products we need to have then inside each component
@pamval @rfellows @scottyaslan @krivera-pentaho @annapopova1 @plagoa please review
dependent of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/462
=> [BACKLOG-4044]

package-res/reportviewer/reportviewer.js
- Moved the glass pane hide, allowing it to occur every time the submit ended, even if the prompts still need an input from the user
@pamval @krivera-pentaho @annapopova1 @rfellows @scottyaslan @plagoa please review
Dont merged it yet. Tomorrow i want to do more tests and check every unit test. But the implementation should be finished
=> [BACKLOG-4038]

src/org/pentaho/reporting/platform/plugin/cache/PentahoDataCache.java, test-src/org/pentaho/reporting/platform/plugin/MockTableModel.java, test-src/org/pentaho/reporting/platform/plugin/cache/PentahoDataCacheTest.java
When caching data via the CachingDataFactory, the data is added to the PentahoDataCache.  The CachingDataFactory expects to have a different TableModel returned in order to close the original one, if it is a CloseableTableModel.
The PentahoDataCache always returns the original TableModel causing the CachingDataFactory to skip closing the original TableModel.  This leaves the ResultSet and a corresponding cursor open within Oracle.  This can lead to "maximum open cursor limit exceeded" errors in Oracle.
This is related to support request #60653 on support.pentaho.com.
=> [BISERVER-12767] Resolve issue where the ScrollableResultSetTableModel is not closed after caching

src/org/pentaho/reporting/platform/plugin/ReportContentUtil.java
Additional pull-request to https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/177
Fix updated for the case when user set 'Allow multiple selections' and choose only one option.
@pamval 
Please review.
=> PDB-1869 - Dashboard displays a blank PIR report if it contains a Prompt with option 'Allow multiple selections'(Additional pull-request)

package-res/reportviewer/reportviewer-prompt.js, package-res/reportviewer/reportviewer.js
Checked Report Viewer on biserver-ee-7.0-QAT-37 and found that the plugin works incorrectly.
Fixed next issues:
- panel() - is not a function
- incorrect 'this' usage in callback
- can't remove promptPanel argument for submit and getParameterDefinition functions because this behavior is related with PromptPanel implementation (uses promptPanel argument)
=> [BACKLOG-6760] Fixed some issues of prompt usages

package-res/reportviewer/reportviewer-prompt.js
Relates with PIR, fix the problem:
[exec] Tracing dependencies for: pir/module
[exec] Error: Error: Module loading did not complete for: pir/module, reportviewer/reportviewer-main-module, reportviewer/reportviewer-prompt, common-ui/underscore
[exec] The following modules share the same URL. This could be a misconfiguration if that URL only has one anonymous module in it:
[exec] /build-shared/slave2/workspace/master-snapshot/pir-plugin/bin/scriptOutput/common-ui/underscore/underscore.js: common-ui/underscore, underscore
[exec]     at Function.build.checkForErrors (/build-shared/slave2/workspace/master-snapshot/pir-plugin/build-res/pentaho-js-build/r.js:29996:19)
[exec]
=> [BACKLOG-6961] Fixed usage of underscore dependency

src/org/pentaho/reporting/platform/plugin/JobManager.java, src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java, test-src/org/pentaho/reporting/platform/plugin/async/TestInterruptionInterceptionTest.java
This brings:
- tests cleanup - since we don't fork junits we have side effects on code from one test attempts to set somthing to a static context, while in other tests this static context unexpectedly becomes available.
- [BACKLOG-7181] - use mega-greed catch block to catch exception as far as errors. Errors like NoSuchMethod error while jars incompatible with dependencies. We should avoid hang on working status.
- [BACKLOG-7169] - fix job manager to use proper content headers.
=> [BACKLOG-7169],  	[BACKLOG-7181], junit test clean up.

src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java, src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java, test-src/org/pentaho/reporting/platform/plugin/PageableHTMLTest.java
AbstractReportProcessor creates new event when calling listener.reportProcessingFinished/
This new event has default values for the fields, so we can ignore them and just update the status.
Thomas, take a look please.
@tmorgner
=> Backlog 7352 - Fix '-1' row quantity in the end of generation

package-res/reportviewer/reportviewer.js, src/org/pentaho/reporting/platform/plugin/JobManager.java, src/org/pentaho/reporting/platform/plugin/async/AsyncReportState.java, src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java, src/org/pentaho/reporting/platform/plugin/async/IAsyncReportExecution.java, src/org/pentaho/reporting/platform/plugin/async/IAsyncReportListener.java, src/org/pentaho/reporting/platform/plugin/async/IAsyncReportState.java, src/org/pentaho/reporting/platform/plugin/async/IPentahoAsyncExecutor.java, src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java, src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java, src/org/pentaho/reporting/platform/plugin/cache/IReportContent.java, src/org/pentaho/reporting/platform/plugin/cache/ReportContentImpl.java, src/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java, test-src/org/pentaho/reporting/platform/plugin/JobManagerTest.java, test-src/org/pentaho/reporting/platform/plugin/PageableHTMLTest.java
This one is about navigation through still running report.
How it works on UI:
1. ...
2.  User requests a new page.
3.  If generation have already been finished or page is in cache - just fire a job to get the page from cache. :ok_hand: 
If not - send a request to the generation task to store the cache.
When you see that page is now in cache - just fire a job to get it.
How it works on server side:
1. ...
2.  Somebody requested a page.
3.  If page is already available in processor - write to cache as much pages as you have and update generatedPages value.
If not listen to events and do the job when it is.
I've recorderd a short [demo](https://dl.dropboxusercontent.com/u/71148577/page_navigation.webm)
Thomas, please take a look.
@tmorgner
=> Backlog 7204

src/org/pentaho/reporting/platform/plugin/JobManager.java, src/org/pentaho/reporting/platform/plugin/async/AsyncReportStatusListener.java, src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java
Corner case when staus is 'FINISHED' but the future is not done yet.
Don't see an issue in waiting for future completion on content request.
Also minimized amount of time to wait for this case.
@tmorgner  please review
=> [BACKLOG-7597] - Allow to wait for content, optimize waiting time

package-res/reportviewer/reportviewer.js
We simply don't need to generate report from scheduling dialog independently of chosen generation mode.
=> [BACKLOG-7782] - Avoid report generation in scheduling dialog

package-res/reportviewer/reportviewer-prompt.js, package-res/reportviewer/reportviewer.js
Moved the logic of pagination HTML output detection right after the parameter definition parsing.
With latest master changes flag was not initialised properly.
=> [BACKLOG-7291] - Fix pagination control on dashboard

src/org/pentaho/reporting/platform/plugin/JobManager.java, src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java, src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java, src/org/pentaho/reporting/platform/plugin/staging/AsyncJobFileStagingHandler.java, src/org/pentaho/reporting/platform/plugin/staging/IFixedSizeStreamingContent.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java, test-src/org/pentaho/reporting/platform/plugin/staging/AsyncJobFileStagingHandlerTest.java
This brings next fixes for us:
1) We need a special endpoint for pdf viewer plugin now able to send get
request to whatever it want it to send. Since we can't fix chrome, we have
to fix JobManager fot that.
2) We need to keep same content between requests.
So since we expected to keep content we don't clean-up future after
content requested. Instead - we keep a collection of futures. We expect
clean-up when session destroyed. Also content is kept in staging folder.
3) Since we keep content - we introduce new methods for
IFixedSizeStreamingContent.cleanContent() to explicitly clean up content.
And yes - finally we came to a one-more cahce layer - all content is kept in
statging folder during server works.
Pay attention - content for all currently running sessions.
=> [BACKLOG-7598] - Fix chrome pdf viewver plugin bogus behaviour

src/org/pentaho/reporting/platform/plugin/AuditWrapper.java, src/org/pentaho/reporting/platform/plugin/BackgroundJobReportContentGenerator.java, src/org/pentaho/reporting/platform/plugin/ExecuteReportContentHandler.java, src/org/pentaho/reporting/platform/plugin/ParameterContentGenerator.java, src/org/pentaho/reporting/platform/plugin/PluginPerfomanceMonitorContext.java, src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java, src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java, src/org/pentaho/reporting/platform/plugin/async/ReportListenerThreadHolder.java, test-src/org/pentaho/reporting/platform/plugin/BackgroundJobContentGeneratorTest.java, test-src/org/pentaho/reporting/platform/plugin/ExecuteReportContentHandlerTest.java, test-src/org/pentaho/reporting/platform/plugin/PluginPerfomanceMonitorContextTest.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionAuditTest.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionInterruptTest.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionTest.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java
1) Introduce PluginPerfomanceMonitorContext that will provide session info
for reporting perfomance logging.
We will track perfomance metrics with logging table records with
instanceId from tomcat controller and 'message' field in audit log.
2) Re-check audit logging, remove static hard-coded invocation to be able
to mock in junits.
See original jira case for details.
=> [BACKLOG-6745] - enchase perfomance logging with additional info

src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java, src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutionAuditTest.java
- Add cancelled status for cancelled executions
- Fix excessive handler 'handler.getStagingOutputStream()' : we don't need to close it in catch block since we do close it in finally block
- Added tests for execution cancellations in thread pool as detailed as possible.
=> [BACKLOG-7898] - log cancelled status for audit table

package-res/reportviewer/reportviewer.js, test-js/reportviewer-spec.js
[BISERVER-13171] OK button is disabled even if all mandatory settings are specified when scheduling PIR
http://jira.pentaho.com/browse/BISERVER-13171
added afterRender logic
added tests
@tmorgner @mdamour1976 @pentaho-nbaker Could you please review and merge it?
=> [BISERVER-13171] OK button is disabled even if all mandatory settings are specified when scheduling PIR

src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncExecutor.java, test-src/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java, test-src/org/pentaho/reporting/platform/plugin/cache/DeleteOldOnAccessCacheTest.java
It seems that failing test showed a bug in executor. As far as I understand originally future callbacks were executed in the thread from wich they were added. From the guava code I found out that these callbacks lock the thread and simply wait for result. 
`addCallback(future, callback, MoreExecutors.sameThreadExecutor());`
We had a very bad situation when a bunch of long running scheduled reports could consume all threads from the tomcat thread pool and dramatically affect response time.
With the fix callbacks are now executed in our own thread pool.
@tmorgner please take a look.
=> CLEANUP - Fix naughty tests

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
All parameters can have formulas for post-processing and default-values, not only list parameters.
=> [BACKLOG-9668] - Post-processing computation is not working

package-res/reportviewer/paginationTemplate.html, src/org/pentaho/reporting/platform/plugin/output/PaginationControlWrapper.java
It increses the size of the resulting file but solves encoding issues.
@pentaho/orlandocalisbon @pamval please review
=> [BACKLOG-9604] - Escape HTML to avoid encoding issues

package-res/reportviewer/reportviewer.js
Lucky pentahoGet and penahoPost have almost same signature, so to remove parameters from url seems only change all pentahoGet('reportjob' ... ) to a post one implementation.
=> [BACKLOG-10041] - change GET to POST not to overload url with parameters

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java
Ignore any system row limit if the UI is disabled to avoid mess on client side.
=> [BACKLOG-11519]-Ignore system row limit if row limit UI is disabled

src/org/pentaho/reporting/platform/plugin/SimpleReportingComponent.java
Reporting plugin messes it's configuration with PIR configuration.
We could check the inputs and detect that the request is from PIR but it's not very safe because user can pass any parameter from the UI and the code is in open source :)
Let's just add allow to override  the login in PIR itself.
=> [BACKLOG-11570]-Allow to override row limit logic in PIR

src/org/pentaho/reporting/platform/plugin/connection/PentahoCubeFileProvider.java, src/org/pentaho/reporting/platform/plugin/connection/PentahoMondrianConnectionProvider.java, test-src/org/pentaho/reporting/platform/plugin/connection/PentahoMondrianConnectionProviderTest.java
The trick is when user do logout server explicitly call discard on a session object. If under the IPentahoSession is HttpSession exactly http session is discarded. Move over, after a session is discarded report processor attempts to load mondrian cube from repository. Using AOP spring intercept such call and try to validate it according to a user session - but it is discarded since user had logout. So - we cant use http session to authorize such calls, instead, we should use user name instead of obsolete session object. See BACKLOG-9586 for detailed stack-trace (there is really self-exploratory stack-trace).
=> [BACKLOG-9586] - add runAsUser to be able to run with discarded session

package-res/reportviewer/report.html
[BACKLOG-11526] - An arrow is absent on Row Limit drop-down.
Backport of https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/501
@tmorgner please review.
=> Backport of [BACKLOG-11526] - An arrow is absent on Row Limit drop-down.

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java, test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java
While validating PDB-1931 I found a regression caused by BISERVER-13435 fix.
Basically the fix overrides all parameters values disregarding of is it actually a list parameter or not.
With such logic we will lose the default values for the plain parameters.
@AliaksandrDrebenchuk FYI
=> [BISERVER-13435]-fix regression

package-res/reportviewer/reportviewer-prompt.js, src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java, test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java
The 1st commit (java code) is a fix for the stackowerflow which is a regression after Ewok's work.
The 2nd is actually the bug fix. We don't reload the PromptPanel after 6.1 and even don't send a request to server after 7.0, so to show valid value we need to go and set it through widget API.
I'm resetting datespickers only here but probably we want the same logic for other inputs as well.
Please pay attention to date parsing, I assume we always have date in ISO format there.
=> BISERVER-13170-Always send post-processing parameters values to the server

src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java, test-src/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java
One case has slipped out of our sight (and even was covered by a unit test). On the initial parameter call we don't have anything changed but already try to erase something. It causes the erasure of the top level parameter if: a) it is a list b) it has no validation.
=> [BACKLOG-14580]-Don't reset selection on the report opening

core/src/main/javascript/reportviewer/reportviewer-prompt.js, core/src/test/javascript/reportviewer-prompt-spec.js
Enhanced the logic and covered it with tests.
There were several issues:
1) The timezone was added twice, when it was present in the value and the hint was aldo present.
2) Some Ausie and New Zeland timezones blowed things up. For some reason the format for 30/45 minutes timezones is different and not supported by JS dates. We have +09.530 and +11.7545 against regular +0930 and +1145 for Australian Nothern territory and NZ-CHAT timezones. By the way, the values with those timezones are not displayed in PUC ssatrting from a 6.1 GA. I've opend an issue PRD-5879
3) If the date is invalid we won't loop infinitely
=> [BISERVER-13569]-Compare values in datepicker parameters carefully

core/src/main/java/org/pentaho/reporting/platform/plugin/repository/ReportContentLocation.java, core/src/test/java/org/pentaho/reporting/platform/plugin/repository/ReportContentLocationTest.java
- Metadata of generated content now contains RESERVEDMAPKEY_LINEAGE_ID
=> [BISERVER-12930] Not all generated content is deleted after scheduling deletion of generated files

core/src/main/java/org/pentaho/reporting/platform/plugin/repository/ReportContentItem.java, core/src/test/java/org/pentaho/reporting/platform/plugin/repository/ReportContentItemTest.java
JIRA: http://jira.pentaho.com/browse/BACKLOG-17248
Changes the way repository paths are handled for `ReportContentItems` to work around Spring not allowing encoded slashes.
=> [BACKLOG-17248] Fix images/CSS in single-page HTML reports generated in background

core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingAction.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/CachingPageableHTMLOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/DefaultReportOutputHandlerFactory.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/PageableHTMLOutput.java, core/src/test/java/org/pentaho/reporting/platform/plugin/output/DefaultReportOutputHandlerFactoryTest.java
@pentaho/rogueone @tmorgner 
JIRA: https://jira.pentaho.com/browse/BACKLOG-20957
This PR modifies `CachingPageableHtmlOutput` to respect the useJcr flag. The `SimpleReportingAction` class was changed to enable this flag by default (so prpts that are run in the background will store images/css in JCR).
Storing related files in a folder with the prpt name was considered, but not implemented. Since images are reused if the report is cached, output may refer to images from an earlier run the prpt. If the cache is cleared, the images will not be deleted and duplicates will be added to the same folder.  This leads to same confusion as having no folder -- as long as images are reused between runs, the dependencies will be complex. This is really a stopgap solution. A long term solution is …
=> [BACKLOG-20957] Store images/css in the repository for pageable HTML output when the useJcr flag is set

core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleReportingComponent.java, core/src/main/java/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecution.java
This wasn't actually a bug. In Excel 97, the maximum number of allowed rows is 65536. If the file is bigger, it is impossible to generate a proper excel file.  Before the ReportProcessingException was silenced during execution, but now the exception is thrown. Moreover, to give a more descriptive error message, all cascading exceptions' error messages are included.  
Instead of: "Request failed"
The error message is:
" Failed to process the report.
Other failure.
Invalid row number (65536) outside allowable range (0..65535).
"
@pamval @duarteteixeira 
@pentaho-lmartins @ricardosilva88
=> [BISERVER-13775] PUC-Unable to generate report in Excel

core/src/main/java/org/pentaho/reporting/platform/plugin/JobManager.java, core/src/test/java/org/pentaho/reporting/platform/plugin/JobManagerTest.java
@pentaho/tatooine @wseyler @pentaho-lmartins 
* [PRD-6031] Added method to check for disposition type and to use attachment for files that the report cannot put inline, and to use inline for everything else.
* [PRD-6031] Added test to validate new method.
This Pull Request requires the merging of this PR:
https://github.com/pentaho/pentaho-platform/pull/4434
=> [PRD-6031] Exporting a report in Excel via IE gives the filename as "content" instead of giving the prpt's name as filename

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java, core/src/main/java/org/pentaho/reporting/platform/plugin/ReportContentUtil.java, core/src/test/java/org/pentaho/reporting/platform/plugin/ReportContentUtilTest.java
This is one part of 3 PRs for this issue.
The other are:
https://github.com/pentaho/pentaho-reporting/pull/1282
https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1443
@pentaho-lmartins @pentaho/tatooine
=>  [PRD-6070] Date Picker showing incorrect value when client is in different day due to Timezone difference

core/pom.xml, core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterDependencyGraph.java, core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java, core/src/main/javascript/reportviewer/reportviewer-prompt.js, core/src/test/java/org/pentaho/reporting/platform/plugin/ParameterDependencyGraphTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java, core/src/test/javascript/reportviewer-prompt-spec.js
@pentaho/tatooine @ssamora @pentaho-lmartins @tmorgner
* [BISERVER-14306] Added extra functionality and reversed logic for ParameterDependencyGraph
* [BISERVER-14306] Changed boolean logic to check for dependencies
instead of availability and in ParameterDependencyGraph checked for
instance of TableDataFactory to return an empty table instead of null
* [BISERVER-14306] Added extra check for getSelections
* [BISERVER-14306] Updated tests
* [BISERVER-14306] Updated client javascript to ensure the selected
value is set properly when switching date objects (this is generally
working, but for those date objects that have default values, this loses
it's value)
* [BISERVER-14306] Cleanup of javascript and java code
Pull Request is from a set of two PRs:
* …
=> [BISERVER-14306] Multi Value List parameter values are reset after changing output type in a prpt report

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java, core/src/test/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java
@pentaho/tatooine @RPAraujo @ssamora
* [PRD-6038] Added logic to ensure if the "child" is the same parameter name as the known Parameter. With query parameters, sometimes the dependency graph states itself as the dependency. This logic is needed to ensure we don't remove the query parameter from the effectively changed list, so it can keep any variables input by the user.
This PR is part of a set:
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1485
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/743
=> [PRD-6038] Auto-complete feature of Text Box is not working as expected when using a query to limit the results returned.

core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterDependencyGraph.java, core/src/main/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandler.java, core/src/main/java/org/pentaho/reporting/platform/plugin/ReportContentUtil.java, core/src/main/javascript/reportviewer/reportviewer-prompt.js, core/src/test/java/org/pentaho/reporting/platform/plugin/ParameterXmlContentHandlerTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/ReportContentUtilTest.java
date parameters that will provide the option to be set using dynamically-calculated values based on a time interval relative to the time the report is run.  Checks the classic-engine.properties file for param names and injects additional parameters when the report is scheduled to allow selecting a relative date range.
=> [BACKLOG-38398] Allow users to specify the names of specific pairs of

core/src/main/javascript/reportviewer/reportviewer.js
[BACKLOG-39674] In PUC, adding a saved Interactive Report to a new Dashboard is throwing a "Fatal Error Error Parsing parameter information"
[BACKLOG-39674]: https://hv-eng.atlassian.net/browse/BACKLOG-39674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-39701] Error opening chart in new window

core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/XLSXOutput.java
Adding support for new Excel export settings.
See: https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/1045
=> [BISERVER-14865] - Impossible to download PIR reports onto Excel 2007 format once data is past Excel limitations

core/pom.xml, core/src/test/java/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java, pom.xml
There's a race condition when multiple tests in PentahoAsyncReportExecutorTest are run at the same time. The only way to run these one at a time without slowing every other test in the module to a crawl is the `@NotThreadSafe` annotation.
The new dependency is a re-implementation of the original library, which used a problematic license. Check the [readme](https://github.com/stephenc/jcip-annotations) in the repo for more information.
=> [TEST] Unit test fixes for JDK17

core/src/main/javascript/reportviewer/reportviewer-prompt.js
- Ensure dates are compared based on calendar day when time is "00:00:00.000"
- Fetch current browser date and normalize both dates to ignore timezone
- Resolve issue where timezone differences caused incorrect date comparison
@pentaho/tatooine_dev
=> [BISERVER-14919] Compare server and browser dates ignoring timezone

core/pom.xml, core/src/it/java/org/pentaho/reporting/platform/plugin/async/AsyncIT.java, core/src/it/java/org/pentaho/reporting/platform/plugin/async/ReservedIdIT.java, core/src/main/java/org/pentaho/reporting/platform/plugin/BackgroundJobReportContentGenerator.java, core/src/main/java/org/pentaho/reporting/platform/plugin/CacheManagerEndpoint.java, core/src/main/java/org/pentaho/reporting/platform/plugin/DownloadReportContentHandler.java, core/src/main/java/org/pentaho/reporting/platform/plugin/ExecuteReportContentHandler.java, core/src/main/java/org/pentaho/reporting/platform/plugin/JobManager.java, core/src/main/java/org/pentaho/reporting/platform/plugin/SimpleEmailComponent.java, core/src/main/java/org/pentaho/reporting/platform/plugin/connection/CdaPluginLocalQueryBackend.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/EmailOutput.java, core/src/test/java/org/pentaho/reporting/platform/plugin/BackgroundJobContentGeneratorTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/CacheManagerEndpointTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/ExecuteReportContentHandlerTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/JobManagerResponseCodeTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/JobManagerTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/async/FakeLocation.java, core/src/test/java/org/pentaho/reporting/platform/plugin/async/PentahoAsyncReportExecutorTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/async/WriteToJcrTaskTest.java, core/src/test/java/org/pentaho/reporting/platform/plugin/output/EmailOutputTest.java, pom.xml
[BACKLOG-41287]-Upgrading pentaho-platform-plugin-interactive-reporting from Java-EE to Jakarta-EE to support with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41287]-Upgrading pentaho-platform-plugin-interactive-reporting from Java-EE to Jakarta-EE to support with Tomcat-10.X

core/src/main/javascript/reportviewer/dojo/pentaho/reportviewer/GlassPane.js, core/src/main/javascript/reportviewer/reportviewer.js
[PPP-5353]-XSS Findings For Pentaho-platform-plugin-reporting
[PPP-5353]: https://hv-eng.atlassian.net/browse/PPP-5353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-5353]-XSS Findings For Pentaho-platform-plugin-reporting

core/src/main/java/org/pentaho/reporting/platform/plugin/output/EmailOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastCSVOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamHtmlOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastStreamJcrHtmlOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/FastXLSXOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/OutputUtils.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/PDFOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/PNGOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/PlainTextOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/RTFOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlPageableOutput.java, core/src/main/java/org/pentaho/reporting/platform/plugin/output/XmlTableOutput.java
If the `RowLimit` coming from the UI is positive, we use that value, otherwise we user whatever is in `settings.xml`. In case there is no value coming from the UI and there is any problem with the settings, we use -1 (no limit).
=> [PRD-6173] - RowLimit while exporting Excel for PRD report is not working in PUC

core/src/main/java/org/pentaho/reporting/platform/plugin/output/util/ReadableFilterUtil.java, core/src/test/java/org/pentaho/reporting/platform/plugin/output/util/ReadableFilterUtilTest.java
Updated the `DATEVALUE` regular expression to use word boundaries (`\b`) instead of optional parentheses for better accuracy in matching expressions
=> [BACKLOG-44501] fix: update DATEVALUE regex to preserve outer parentheses

core/src/main/javascript/reportviewer/reportviewer-prompt.js
- NPE thrown upon reauthentication, when PIR is opened standalone
- when embedded in, PUC, typically, PUC's every 10s session-timeout detection opens a modal session timeout dialog which prevents PIR's local handling to take effect
Part of PR set: https://github.com/pentaho/pentaho-platform/pull/5915
@pentaho/millenniumfalcon, please, review.
=> fix: incorrect mantle frame detection breaks session-timeout handling [PPUC-108][BISERVER-14841]
